title: Harry Traynor
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Everything technology and that sparks my interest. I am an IT consultant
  specialising in Office 365 and Cloud Technology.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://harrytraynor.io/" # the base hostname & protocol for your site, e.g. http://example.com
show_excerpts: true

# Build settings
#theme: plainwhite
remote_theme: thelehhman/plainwhite-jekyll
plugins:
  - jekyll-feed

plainwhite:
  name: Harry Traynor
  tagline: Consultant. Developer
  date_format: "%b %-d, %Y"
  dark_mode: true
  
  social_links:
    twitter: haztraynor
    github: harrytraynor
    linkedIn: in/harrytraynor
